import type { Metadata } from "next";
import "./globals.css";
import { Nunito_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NunitoSansFont = Nunito_Sans({
  variable: "--nunito-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${NunitoSansFont.variable}`}>
      {children}
    </html>
  );
}
